name: Terraform_async
description: run terraform concurrently
inputs:
  tasks:
    description: "terraform project folders"
    required: true
  verb:
    description: "plan, apply or destroy"
    required: true
    default: plan
  workers:
    description: "insert the number of workers to run concurrently"
    required: true
    default: 2
  version:
    description: "terraform version"
    required: true
    default: "1.7.0"

runs:
  using: docker
  image: docker://ghcr.io/adalbertjnr/async_terraform:latest
